### ISSUE TITLE
Not compatiple with Windows 10 build 10.0.17134

### ISSUE THREAD

**Issue by howej** [morrisjdev/FileContextCore#1]
I get following error when I'm trying to install the nuget package in a UWP application.

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Package FileContextCore 2.1.0 is not compatible with uap10.0.17134 (UAP,Version=v10.0.17134) / win10-arm. Package FileContextCore 2.1.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)			0

**Comment by morrisjdev** [comment]
The package is compatible with .Net Standard and .Net Core. It is not intended to be used with UWP. Entity Framework Core is not compatible with UWP as well.
