### ISSUE TITLE
How to retrive all records from the data source

### ISSUE THREAD

**Issue by balukantu** [morrisjdev/FileContextCore#13]
Hi Morris,

I am working on a service fabric project and I want to implement a custom EF core provider so I have gone through a few existing providers and the FileContext provider. 

The FileContext provider suites perfect for my requirements. I have made the necessary changes and it is working now.
I am able to perform CRUD operations on the tables and get all records from the source.

Here I observed one scenario, i.e If we want to get all records, we need to use ToList() method otherwise the data is not populated.

Example:

Below are two classes and I would like to join these entities.

`
Class Student
{
    [Key]
    public Guid StudentId{ get; set; }

    public Guid DepartmentId { get; set; }
	
    public string StudentName { get; set; }
}
`

`
Class Department

{
    [Key]
    public Guid DepartmentId { get; set; }
    public string DeptName { get; set; }
}
`

Below is the query in LINQ and executed this scenario, however, the result is null.

	var result = from student in dbContext.Students
				join department in dbContext.Departments on student.DepartmentId equals department.DepartmentId
				select new
				 {
					student.StudentName,
				 };

If we modify the above scenario as below, it is giving the expected result.

	var result = from student in dbContext.Students.ToList()
				join department in dbContext.Departments.ToList() on student.DepartmentId equals department.DepartmentId
				select new
				 {
					student.StudentName,
				 };

**Below is my observation:**
We have to get the records using dbContext.Students.ToList() and then perform join.

**Question:**
Can we get all records using dbContext.Students and proform join condition instead of using ToList()

**Comment by morrisjdev** [comment]
Hi.
I am currently in vacation and will look into this in the new year.

But did you try to do this operation with another EF core provider like inmemory or mysql? I'm not sure if it works there.

Are you required to resolve the relation manually with a join?
 
Best regards

Morris

**Comment by balukantu** [comment]
Hi Morris,

Thanks for the quick response.

With EF Core SQL provider, we can get the values directly using "dbContext.Table()".

This is not only for resolving the relations among collections. If I want to do some joins or write LINQ queries, I need to get the whole data and perform the operation.

So I just tried getting the records and joining them.

**Comment by balukantu** [comment]
Hi Morris,

I made a few changes in the provider hence the response was not coming. I tried debugging and now able to get the records. 

Thanks for the FileProvider.

**Comment by morrisjdev** [comment]
Good to hear. Sorry that I did not have the time to help you.

Good luck for the future and best regards
