### ISSUE TITLE
Custom ISerializer - binary file

### ISSUE THREAD

**Issue by codemonkey85** [morrisjdev/FileContextCore#16]
Hello,

I was wondering if you might consider opening the ISerializer interface and allowing UseFileContextDatabase() to accept a custom ISerializer. My specific aim is to use a custom binary serializer so I can use a binary file as my database. My DbContext would have DbSets of classes that have been written using StructLayout annotations.

**Comment by morrisjdev** [comment]
Good point. I'll take a look into it.

**Comment by morrisjdev** [comment]
Hi.

The version 3.3.0 of FileContextCore now supports custom ISerializer, IFileManager and IStoreManager.
Feel free to take a look and let me know what you think about it.

Thank you for the idea.

Best regards

Morris

**Comment by codemonkey85** [comment]
Very cool. Thank you!
