### ISSUE TITLE
[Feature Request] Instantiate services through DI

### ISSUE THREAD

**Issue by KuraiAndras** [morrisjdev/FileContextCore#24]
Right now if you want to create a custom IFileManager (or ISerializer) you can only have a class with a default constructor. It would be nice for them to have any dependency you want.

**Comment by morrisjdev** [comment]
Hi.
Thank you for the good idea.
Should only be a small adjustment.
I'll implement it soon.

**Comment by morrisjdev** [comment]
Thank you. I added this feature in version 3.4.0.
