### ISSUE TITLE
Remove redundant key column

### ISSUE THREAD

**Issue by dfyx** [morrisjdev/FileContextCore#6]
The `Key` (or `__Key__`) column is fully redundant. EFCore has easy ways to find out which of the data columns are part of the primary key (through `entityType.GetKeys().First(k => k.IsPrimaryKey).GetProperties()`. This is especially important for CSV where some legacy formats might expect an exact set of available columns.

I have this change fully implemented and can provide it as soon as #5 is merged (as it relies on some changes that I made there)

**Comment by morrisjdev** [comment]
Hi.
Good idea. I already wanted to do this, but it was a bit complicated because i also wanted to support composite keys. I implemented it and will publish the new version soon.

Thank you
