### ISSUE TITLE
Having an issue with a Nullable

### ISSUE THREAD

**Issue by j13leach** [morrisjdev/FileContextCore#9]
I had an issue with Nullable<Guid> I put in a PR for a fix

**Comment by j13leach** [comment]
Actually it looks like Nullable across the board... Looking into it

**Comment by j13leach** [comment]
Submitted new PR

**Comment by morrisjdev** [comment]
Thank you for the contribution. I merged it and will create a new release on nuget soon.

**Comment by morrisjdev** [comment]
The new version is 3.0.1.

**Comment by j13leach** [comment]
Thanks man! Using your library for an integration test idea. It's pretty slick
